const Texts = {
  FA: {
    key: 'FA',
    txtAppName: 'مدل لاک و ناخن',
    txtSetting: 'تنظیمات',
    txtExitApp: 'خروج از برنامه',
    txtDefault: 'پیشفرض',
    txtDarkMode1: 'حالت تیره 1',
    txtDarkMode2: 'حالت تیره 2',
    txtchocolate: 'شکلاتی',
    txtRedBlack: 'قرمز-مشکی',
    txtBrownBlue: 'قهوه‌ای-آبی',
    txtPinkBlue: 'صورتی-آبی',
    txtGreenRed: 'سبز-قرمز',
    txtYellowBlue: 'زرد-آبی',
    txtBrownGold: 'قهوه‌ای-طلایی',
    txtPinkGreen: 'صورتی-سبز',
    txtGreyYellow: 'خاکستری-زرد',
    txtGreywhite: 'خاکستری-سفید',
    txtColorfull: 'رنگارنگ',
    txtPink: 'صورتی',
    txtChooseFont: 'انتخاب فونت',
    //برعکسه
    txtLanguageChanged: 'Language changed successfully',
    txtThemeChanged: 'تم برنامه با موفقیت تغییر کرد.',
    txtTheme1: 'فونت 1 (پیشفرض)',
    txtTheme2: 'فونت 2',
    txtTheme3: 'فونت 3',
    txtTheme4: 'فونت 4',
    txtTheme5: 'فونت 5',
    txtTheme6: 'فونت 6',
    txtFontChanged: 'فونت برنامه با موفقیت تغییر کرد.',
    txtChooseTheme: 'انتخاب پوسته',
    txtChooseLanguage: 'انتخاب زبان',
    txtMainPage: 'صفحه اصلی',
    txtWellcome: 'خوش آمدید',
    txtBeingSpecialIsWorthyOfYou: 'خاص بودن برازنده شماست',
    txtLoading: 'در حال بارگذاری ...',
    txtSlogen: 'محنصر به فرد باش! سلامت باش! خوشحال باش !',
    txtSearchHashtagPlaceHolder: 'جستجوی هشتگ   ( برای نمونه : #فرنچ )',
    txtHandNails: 'ناخن های دست',
    txtFoofNails: 'ناخن های پا',
    txtShouldHasHashtag: 'عبارت جستجو شده باید دارای # باشد',
  },
  EN: {
    key: 'EN',
    txtSetting: 'Setting',
    txtExitApp: 'Exit App',
    txtAppName: 'Nail Polish',
    txtDefault: 'default',
    txtDarkMode1: 'Dark mode 1',
    txtDarkMode2: 'Dark mode 2',
    txtchocolate: 'Chocolate',
    txtRedBlack: 'Red-Black',
    txtBrownBlue: 'Brown-Blue',
    txtPinkBlue: 'Pink-Blue',
    txtGreenRed: 'Green-Red',
    txtYellowBlue: 'Yellow-Blue',
    txtBrownGold: 'Brown-Gold',
    txtPinkGreen: 'Pink-Green',
    txtGreyYellow: 'Grey-Yellow',
    txtGreywhite: 'Grey-White',
    txtColorfull: 'Colorful',
    txtPink: 'Pink',
    txtChooseFont: 'Choose Font',
    //برعکسه
    txtLanguageChanged: 'زبان برنامه با موفقیت تغییر کرد',
    txtThemeChanged: 'Theme changed successfully.',
    txtTheme1: 'Font 1 (default)',
    txtTheme2: 'Font 2',
    txtTheme3: 'Font 3',
    txtTheme4: 'Font 4',
    txtTheme5: 'Font 5',
    txtTheme6: 'Font 6',
    txtFontChanged: 'Font changed successfully.',
    txtChooseTheme: 'Choose Theme',
    txtChooseLanguage: 'Choose Language',
    txtMainPage: 'Main Page',
    txtWellcome: 'Wellcome',
    txtBeingSpecialIsWorthyOfYou: 'Being special is worthy of you',
    txtLoading: 'Loading...',
    txtSlogen: 'Be kind to the individual! Be healthy! Be happy !',
    txtSearchHashtagPlaceHolder: 'Search Hashtags ( Example : #sharp )',
    txtHandNails: 'Hands Nails',
    txtFoofNails: 'Foot Nails',
    txtShouldHasHashtag: 'Searching sentece should have #',
  },
};
export default Texts;
